### ISSUE TITLE
Disqus is not showing or invisible for octopress 3.0

### ISSUE THREAD

**Issue by NoahDragon** [yang-wei/simplified#12]
The comments in code caused this problem. To fix it is also simple, remove the comment lines in following files:
[source/_layouts/default.html](https://github.com/yang-wei/simplified/blob/e8331e2396ad8cdd96fbadf1a75306cc754bde47/source/_layouts/default.html#L12)
[source/_layouts/post.html](https://github.com/yang-wei/simplified/blob/e8331e2396ad8cdd96fbadf1a75306cc754bde47/source/_layouts/post.html#L35-L43)

**Comment by yang-wei** [comment]
@NoahDragon I just know there is 3.0 coming. 

Thanks for the issue. I havn't got any time to look into this yet but would like to know if my theme is working properly on 3.0 version. Mind to share?

**Comment by NoahDragon** [comment]
Thanks for reply. 
So far, it's working great. I haven't encountered any other issues yet.
Here is my [site](http://abnerchou.me).
